### ISSUE TITLE
Excel export only works on first page

### ISSUE THREAD

**Issue by FreakwaveCGN** [mentatpsi/OSGenome#11]
The export to excel function only exports the content of the first page, so max. 250 entries. Could this be changed? Thank you!
Dennis

**Comment by mentatpsi** [comment]
I should be able to make that change. I've actually done that with another application of Kendo Grid. Shouldn't be an issue.

**Comment by mentatpsi** [comment]
The following fix was implemented to handle exporting all Items
https://github.com/mentatpsi/OSGenome/commit/98976f8ac71f23b94bc897c551b26e2a69d03cbc
