### ISSUE TITLE
Missing files?   No such file or directory: './data/snpDict.json'

### ISSUE THREAD

**Issue by jjv5** [mentatpsi/OSGenome#12]
Is there additional data  that needs to be downloaded from somewhere else?

I am using a test data set from:   https://my.pgp-hms.org/public_genetic_data?data_type=23andMe

and get this error:
FileNotFoundError: [Errno 2] No such file or directory: './data/snpDict.json'

when running this command:

python SNPedia/DataCrawler.py -f /Users/jjv5/Desktop/osgenome/genome_Daniel_Munro_Full_20141013190727.txt

**Comment by mentatpsi** [comment]
Hi,
 
Just fixed this in the latest commit https://github.com/mentatpsi/OSGenome/commit/b05eae4727be6e2eb243bc478152704dad09361a 

Let me know how this works for you
